### ISSUE TITLE
Ошибка Unable to extract video data 

### ISSUE THREAD

**Issue by xvladqt** [alex2844/youtube-music#1]
При скачивании всех треков, на некоторых вылетает ошибка "ERROR: QCUGGbrTnSA: YouTube said: Unable to extract video data" 

```
[youtube-music] Starting: ГОРГОРОД/Колыбельная
[youtube] QCUGGbrTnSA: Downloading webpage
ERROR: QCUGGbrTnSA: YouTube said: Unable to extract video data
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/youtube.py", line 1892, in _real_extract
    raise ExtractorError(
youtube_dl.utils.ExtractorError: QCUGGbrTnSA: YouTube said: Unable to extract video data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/ymusic", line 165, in <module>
    main(sys.argv[1:])
  File "/usr/local/bin/ymusic", line 145, in main
    playlist(None, ('-d' in args) or ('--doubles' in args))
  File "/usr/local/bin/ymusic", line 82, in playlist
    download(song['videoId'], fname)
  File "/usr/local/bin/ymusic", line 59, in download
    ydl.download(['https://www.youtube.com/watch?v='+id])
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/YoutubeDL.py", line 2018, in download
    res = self.extract_info(
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/YoutubeDL.py", line 820, in extract_info
    self.report_error(compat_str(e), e.format_traceback())
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/YoutubeDL.py", line 625, in report_error
    self.trouble(error_message, tb)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/YoutubeDL.py", line 595, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: QCUGGbrTnSA: YouTube said: Unable to extract video data

```

**Comment by alex2844** [comment]
QCUGGbrTnSA - я так понимаю это id трека? Если да, - то доступ к нему ограничен

![Screenshot 2020-07-31 at 18 02 42](https://user-images.githubusercontent.com/18526177/89037523-13250f00-d358-11ea-848b-f790f04e262d.png)

Для того чтоб посмотреть id - нужно найти этот трек в плейлисте или в избранном на youtube music и нажать на него правой -> Поделиться

**Comment by xvladqt** [comment]
Да, но эта ошибка появляется при использовании --all, где нет возможности указывать другие id. Может добавить опцию, для пропуска треков с невалидными id ? try-except ? Сделал бы сам, но слабо разбираюсь в Python

**Comment by alex2844** [comment]
Хорошо, сделаю

**Comment by xvladqt** [comment]
Я пока у себя сделал так :
```python
def download(id, title=None):
    ...
    try:
        with youtube_dl.YoutubeDL({
            'format': 'bestaudio/best',
            'postprocessors': [{
                'key': 'FFmpegExtractAudio',
                'preferredcodec': 'mp3',
                'preferredquality': '0'
            }],
            'writethumbnail': True,
            'outtmpl': title+'.%(etx)s',
        }) as ydl:
            ydl.download(['https://www.youtube.com/watch?v='+id])
    except Exception:
        print('Exception skip')
        return False;

def playlist(id, doubles=False):
    ...
                    status = download(song['videoId'], fname)
                    if(status == False):
                        continue
```
Но не знаю, насколько это правильно, просто хак.

**Comment by alex2844** [comment]
Готово. Добавил --skip-error

`ymusic --all --skip-error`

**Comment by xvladqt** [comment]
Спасибо, работает.
