### ISSUE TITLE
An attempt to download Liked songs or All collection leads to 403 error

### ISSUE THREAD

**Issue by kpspu** [alex2844/youtube-music#6]
I run a script on a Colab with my Liked Playlist and encountered this error. It would be nice to have a list of the problematic songs.

ID: https://music.youtube.com/playlist?list=LM
Traceback (most recent call last):
  File "/dev/fd/63", line 107, in playlist
  File "/usr/local/lib/python3.7/dist-packages/ytmusicapi/mixins/playlists.py", line 66, in get_playlist
    response = self._send_request(endpoint, body)
  File "/usr/local/lib/python3.7/dist-packages/ytmusicapi/ytmusic.py", line 133, in _send_request
    raise Exception(message + error)
Exception: Server returned HTTP 403: Forbidden.
The caller does not have permission

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/dev/fd/63", line 198, in <module>
  File "/dev/fd/63", line 195, in main
  File "/dev/fd/63", line 180, in main
  File "/dev/fd/63", line 111, in playlist
  File "/usr/local/lib/python3.7/dist-packages/ytmusicapi/mixins/playlists.py", line 66, in get_playlist
    response = self._send_request(endpoint, body)
  File "/usr/local/lib/python3.7/dist-packages/ytmusicapi/ytmusic.py", line 133, in _send_request
    raise Exception(message + error)
Exception: Server returned HTTP 403: Forbidden.
The caller does not have permission

**Comment by kpspu** [comment]
A real reason for this error might be the "Private" status of Liked songs. Maybe there is some workaround to add Liked songs to an ordinar shared Playlist but I didn't find a working solution.

**Comment by alex2844** [comment]
Загрузка возможна только публичных треков.
Если трек не доступен в режиме инкогнито, то он не загрузится.

**Comment by kpspu** [comment]
Yes, exactly! I moved all my 4000 liked songs into the "public" playlist and everything worked like a charm with a "download a playlist" option. I can confirm the durabiltiy of this script on 4000 songs now. If my runtime was expired in Colab, I simply rerun script and it skipped all downloaded songs automatically. Great job! Thanks!
